sudo: required

os:
  - windows
  - linux

language: cpp
services:
  - docker
before_install:
  - docker build -t friendlyhello .
  - docker run -itd --name build friendlyhello
script:
  - docker exec build bash -c "mkdir build && cd build && conan install .. --build portaudio && cmake .. -G \"Unix Makefiles\" && cmake --build ."
